### ISSUE TITLE
Needs basic instructions in README

### ISSUE THREAD

**Issue by maskott** [jantman/docker-zoneminder#3]
@jantman Thank you for your work! I know this repo is just a personal project, but please please help me out and post some super basic instructions on how to use in the readme. I know just enough about docker to be dangerous!

So far I used `docker pull` to grab your code from Docker hub. I tried `docker run jantman/docker-zoneminder` but it hangs on startup during and then repeats `MariaDB not answering ping yet; try again in 3s...` indefinitely. I am sure I haven't properly set up the environment variables yet. I see there are .EXAMPLE files in the repo, but I have no idea where to find them on the system I used the `docker pull` command on.

I'm desperately trying to get a containerized instance of Zoneminder set up on a new server I'm building. Thank you in advance for any light you might shed!

**Comment by jantman** [comment]
Hey @maskott . Sorry about that. I'll try to get something added to the README in the next few days, but in the mean time, hopefully this will get you started:

1. Either clone this git repo on the machine where you want to run it, or download the two `docker-compose` files and all of the `EXAMPLE` files to that machine.
2. Remove the `EXAMPLE.` from the example file names, and edit the content of the files as needed. These are all documented elsewhere, and are all related to the ZM Event Notification server (ZMES) and object detection. If you don't care about ZMES and object detection, then these files can just be left as-is.
3. If the `docker-compose` command isn't already available on your system, [install docker-compose](https://docs.docker.com/compose/install/).
4. In whichever docker-compose file you use (or both), change `jantman/docker-zoneminder:devel` to `jantman/docker-zoneminder:1.36.33-jantman3`
5. From that same directory, `docker-compose up` should start the database and then zoneminder. If you also want the MLAPI object detection, you can use `docker-compose -f docker-compose-mlapi.yml up`

This should get everything up and running. Please note, however, that this is really just a demo method - you'll want to start the docker containers up in a way that starts them at boot in the right order and restarts them if they die (i.e. systemd units) and at a minimum you'll also want to ensure that you're backing up the MariaDB database content (outside the scope of this project's docs) and whatever you need to backup from ZoneMinder (i.e. if you want to back up events).

I hope this can get you started. The docker-compose files should provide a decent reference for how this container is expected to run. Note that, as you'll see, this image needs a separate MySQL/MariaDB database; that's provided by a separate image in the docker-compose files.

**Comment by maskott** [comment]
@jantman Thank you so much for taking the time to point me in the right direction! Using your instructions, I was able to get the container running. I'm just starting to get things set up now. I think I may need to go back and find where to edit to give myself access to some storage to save all of the recordings and events to. Thanks again and I look forward to more details in the README when you have a chance. 🙏

**Comment by jantman** [comment]
I've added my post above to the README. If there's anything else that you feel I should add, please let me know.
